services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fulbito
      POSTGRES_PASSWORD: fulbito
      POSTGRES_DB: fulbito
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: