name: fulbito-yml

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Build
        run: pnpm build

  deploy-backend:
    needs: lint-test-build
    runs-on: ubuntu-latest
    outputs:
      backend_url: ${{ steps.get_url.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy Backend
        id: get_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
        run: |
          ARGS="--token=$VERCEL_TOKEN"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            ARGS="$ARGS --prod"
          fi
          URL=$(vercel deploy apps/backend $ARGS)
          echo "url=$URL" >> $GITHUB_OUTPUT

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy Frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
        run: |
          ARGS="--token=$VERCEL_TOKEN"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            ARGS="$ARGS --prod"
          fi
          vercel deploy apps/web $ARGS \
            --build-env NEXT_PUBLIC_API_URL=${{ needs.deploy-backend.outputs.backend_url }}